/**
 * Interface for meal suggestions generated by the LLM
 */
export interface MealSuggestion {
  name: string;
  description: string;
  ingredients: string[];
  preparationSteps: string[];
  cookingTime: string;
  pickyEaterTips?: string;
  rawResponse?: string; // For fallback/debugging
}

