/**
 * Interface for meal suggestions generated by the LLM
 */
export interface MealSuggestion {
  name: string;
  description: string;
  ingredients: string[];
  preparationTime: string;
  cookTime: string;
  instructions: string[];
  pickyEaterTips?: string;
}